"""empty message

Revision ID: 1dbbf891d16c
Revises: 6b4ce873113a
Create Date: 2024-12-28 16:25:17.062081

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1dbbf891d16c"
down_revision: Union[str, None] = "6b4ce873113a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("carts", "created_at", type_=sa.DateTime(timezone=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("carts", "created_at", type_=sa.DateTime(timezone=False))
    # ### end Alembic commands ###
