"""connection between user and cart

Revision ID: 6b4ce873113a
Revises: c3a35e25aaf5
Create Date: 2024-12-28 15:47:48.375223

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6b4ce873113a"
down_revision: Union[str, None] = "c3a35e25aaf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    # # op.add_column('carts', sa.Column('user_id', sa.Integer(), nullable=True))  # Делаем null, чтобы избежать ошибки
    #
    # # Здесь мы делаем попытку привязать корзину к юзеру.
    # # Скорее всего вам понадобится еще раз пересмотреть эту часть
    # # и придумать, как привязать корзину к юзеру.
    # # conn = op.get_bind()
    # # conn.execute(text(
    #     """

    #     UPDATE carts
    #     SET user_id = 1  -- Replace with the logic to determine user_id
    #     WHERE user_id IS NULL;
    # """
    # # ))
    # # op.alter_column('carts', 'user_id', nullable=False)
    op.create_foreign_key(
        "fk_carts_users_id", "carts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_unique_constraint("uq_carts_user_id", "carts", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_carts_user_id", "carts", type_="unique")
    op.drop_constraint("fk_carts_users_id", "carts", type_="foreignkey")
    op.drop_column("carts", "user_id")
    # ### end Alembic commands ###
