"""empty message

Revision ID: ddaffc44c42e
Revises: 1dbbf891d16c
Create Date: 2025-01-06 14:03:15.837504

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ddaffc44c42e"
down_revision: Union[str, None] = "1dbbf891d16c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_seller",
            sa.Boolean(),
            nullable=False,
            server_default=sa.sql.expression.false(),
        ),
    )

    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("is_seller", server_default=sa.sql.expression.false())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_seller")
    # ### end Alembic commands ###
