"""empty message

Revision ID: e8c71a0b6f0e
Revises: ecc8d53c974f
Create Date: 2024-12-25 14:50:24.551939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e8c71a0b6f0e"
down_revision: Union[str, None] = "ecc8d53c974f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_username_constraint", "users", ["username"])
    op.create_unique_constraint("unique_email_constraint", "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_username_constraint", "users", type_="unique")
    op.drop_constraint("unique_email_constraint", "users", type_="unique")
    # ### end Alembic commands ###
